# Generated by Django 5.0.3 on 2024-04-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4),
        ),
    ]
