# Generated by Django 5.0.3 on 2024-04-08 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=2, verbose_name='Символ валюты')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Код валюты')),
                ('short_name', models.CharField(max_length=3, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод средств')], max_length=20),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Id платежа')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод средств')], max_length=20, verbose_name='Тип платежа')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency', verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.application', verbose_name='Заявка')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency', verbose_name='Валюта'),
        ),
    ]
