# Generated by Django 5.0.3 on 2024-04-04 10:23

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=255, unique=True, verbose_name='Логин')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('type', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Тип аккаунта')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Телефон должен быть в формате: +996999999900', regex='^\\+?1?\\d{11}$')], verbose_name='Телефон')),
                ('sms_notification', models.BooleanField(default=False, verbose_name='Уведомление по смс')),
                ('groups', models.ManyToManyField(blank=True, related_name='my_custom_related_name', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='my_custom_related_name', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('Муж', 'Мужской'), ('Жен', 'Женский')], default='Муж', max_length=30, verbose_name='Пол')),
                ('passport_photo_reversal', models.ImageField(blank=True, upload_to='passport_photo_reversal', verbose_name='Фото разворота паспорта')),
                ('passport_photo_registered_address', models.ImageField(blank=True, upload_to='passport_photo_reversal', verbose_name='Фото страницы с пропиской')),
                ('registered_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Прописка')),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(default='', max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator('^[0-9]+$')], verbose_name='Номер паспорта')),
                ('subdivision_code', models.CharField(default='', max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Код подразделения')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнительная информация о пользователе',
                'verbose_name_plural': 'Дополнительная информация о пользователе',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
